Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2018-12, with the labels that each got.

#18 Fix Debug build segfault on Ubuntu
  Source/Lib/ASM_AVX2/EbComputeSAD_SadLoopKernel_AVX512.c
Labels: bug

#42 Clean up CMake on Windows
  .gitignore
  Build/windows/generate_vs17.bat
Labels: Clean up

#37 External API
  CMakeLists.txt
  Source/API/EbApi.h
  Source/API/EbApi.version
  Source/API/EbErrorCodes.h
  Source/API/EbTime.h
  Source/App/EbAppConfig.c
  Source/App/EbAppContext.c
  Source/App/EbAppMain.c
  Source/App/EbAppProcessCmd.c
  Source/App/EbTime.c
  Source/Lib/C_DEFAULT/EbTransforms_C.c
  Source/Lib/Codec/CMakeLists.txt
  Source/Lib/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Codec/EbAvcStyleMcp.c
  Source/Lib/Codec/EbAvcStyleMcp.h
  Source/Lib/Codec/EbCabacContextModel.c
  Source/Lib/Codec/EbCodingLoop.c
  Source/Lib/Codec/EbComputeMean.h
  Source/Lib/Codec/EbComputeSAD.h
  Source/Lib/Codec/EbDeblockingFilter.c
  Source/Lib/Codec/EbDeblockingFilter.h
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEncodeContext.c
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbEntropyCoding.h
  Source/Lib/Codec/EbErrorHandling.h
  Source/Lib/Codec/EbFullLoop.c
  Source/Lib/Codec/EbInitialRateControlProcess.c
  Source/Lib/Codec/EbInterPrediction.c
  Source/Lib/Codec/EbIntraPrediction.c
  Source/Lib/Codec/EbIntraPrediction.h
  Source/Lib/Codec/EbMcp.h
  Source/Lib/Codec/EbMcpTables.c
  Source/Lib/Codec/EbMeSadCalculation.h
  Source/Lib/Codec/EbModeDecision.c
  Source/Lib/Codec/EbModeDecisionConfiguration.c
  Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Codec/EbModeDecisionProcess.c
  Source/Lib/Codec/EbMotionEstimation.c
  Source/Lib/Codec/EbMotionEstimationProcess.c
  Source/Lib/Codec/EbPackUnPack.h
  Source/Lib/Codec/EbPacketizationProcess.c
  Source/Lib/Codec/EbPictureAnalysisProcess.h
  Source/Lib/Codec/EbPictureDecisionProcess.c
  Source/Lib/Codec/EbPictureManagerProcess.c
  Source/Lib/Codec/EbPictureOperators.c
  Source/Lib/Codec/EbPictureOperators.h
  Source/Lib/Codec/EbProductCodingLoop.c
  Source/Lib/Codec/EbRateControlProcess.c
  Source/Lib/Codec/EbRateDistortionCost.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Codec/EbSampleAdaptiveOffset.h
  Source/Lib/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Codec/EbTransforms.c
  Source/Lib/Codec/EbTransforms.h
  Source/Lib/Codec/EbUtility.c
  Source/SimpleApp/EbSimpleAppContext.c
  Source/SimpleApp/EbSimpleAppMain.c
Labels: Clean up

#46 Thread Affinity
  Docs/SVT-HEVC_Encoder_User_Guide.pdf
  Source/API/EbApi.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppContext.c
  Source/App/EbAppMain.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbThreads.h
  Source/SimpleApp/EbSimpleAppContext.h
Labels: enhancement

#48 FFmpeg Plugin: Fix build fail when SVT-HEVC API change
  ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
Labels: bug
