Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2018-11, with the labels that each got.

#16 lib/system/EbEncDecProcess: Coding style clean up.
  Source/Lib/System/EbEncDecProcess.c
Labels: Clean up

#15 Terminate sample app with unrecognized parameters
  Source/App/EbAppConfig.c
Labels: enhancement

#21 Fix build failure for O0 optimization level
  Source/Lib/Codec/EbCoeffEstimation_Intrinsic.c
  Source/Lib/Codec/EbMdRateEstimation.c
  Source/Lib/Codec/EbProductCodingLoop.c
  Source/Lib/Codec/EbRateDistortionCost.c
  Source/Lib/Codec/EbTransforms.c
  Source/Lib/System/EbPictureAnalysisProcess.c
  Source/Lib/System/EbSourceBasedOperationsProcess.c
Labels: Clean up

#5 VBR Crash Fix
  Source/API/EbErrorCodes.h
  Source/App/EbAppProcessCmd.c
  Source/Lib/System/EbInitialRateControlProcess.c
  Source/Lib/System/EbPictureControlSet.h
Labels: bug
