Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2019-11, with the labels that each got.

#407 Fix reading overflow when estimating bits for SAO offset values in 10bit
  Source/Lib/Codec/EbMdRateEstimation.c
Labels: bug

#404 Matched the default configuration parameters between README and encoder.
  Docs/svt-hevc_encoder_user_guide.md
  Source/API/EbApi.h
  Source/Lib/Codec/EbEncHandle.c
Labels: Clean up

#410 Fix pAppPrivate not propagating to the output.
  Source/Lib/Codec/EbEncHandle.c
Labels: Clean up

#406 Fix integer wrap-around in fillerBytes for CBR VBV.
  Source/Lib/Codec/EbPacketizationProcess.c
Labels: bug

#411 Add missing vbv initial value in library
  Source/Lib/Codec/EbEncHandle.c
Labels: Clean up

#412 GStreamer plugin: update pAppPrivate related comments
  gstreamer-plugin/gstsvthevcenc.c
Labels: gstreamer

#398 10bit YUV422 2bit compressed
  Source/App/EbAppConfig.c
  Source/App/EbAppProcessCmd.c
  Source/Lib/Codec/EbCodingLoop.c
  Source/Lib/Codec/EbEncHandle.c
Labels: enhancement

#408 Fixed the hang issue with each EOS frame.
  Source/Lib/Codec/EbPictureDecisionProcess.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
Labels: bug

#418 Decimal value of level
  Source/Lib/Codec/EbEncHandle.c
Labels: Clean up

#417 Removed the redundant LcuParamsCtor() calling.
  Source/Lib/Codec/EbSequenceControlSet.c
  Source/Lib/Codec/EbSequenceControlSet.h
Labels: Clean up

#135 macOS support
  .travis.yml
  CMakeLists.txt
  Source/App/EbTime.c
  Source/Lib/ASM_SSE2/EbMcp_Intrinsic_SSE2.c
  Source/Lib/ASM_SSE2/EbTransforms_Intrinsic_SSE2.c
  Source/Lib/ASM_SSE2/x64inc.asm
  Source/Lib/ASM_SSSE3/EbMcp_Intrinsic_SSSE3.c
  Source/Lib/Codec/EbCodingLoop.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbThreads.c
Labels: build, enhancement

#422 Safe string functions refactor
  Source/App/CMakeLists.txt
  Source/App/EbAppConfig.h
  Source/App/EbAppInputy4m.c
  Source/App/EbAppString.c
  Source/App/EbAppString.h
  Source/Lib/Codec/CMakeLists.txt
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbString.c
  Source/Lib/Codec/EbString.h
Labels: Clean up

#424 YUV444 10bit compressed
  Source/App/EbAppConfig.c
  Source/Lib/Codec/EbCodingLoop.c
Labels: enhancement

#426 Fixed the IDR insertion failure regression.
  Source/Lib/Codec/EbPictureDecisionProcess.c
Labels: bug

#428 Fix wrong core number print
  Source/Lib/Codec/EbEncHandle.c
Labels: Clean up
