Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2019-12, with the labels that each got.

#435 Fix BDRate regression
  Source/App/EbAppConfig.c
Labels: Clean up

#436 Fix reading input for fifo in ReadInputFrames
  Source/App/EbAppInputy4m.c
  Source/App/EbAppProcessCmd.c
Labels: bug

#429 Conflicts: Fix conflicts with SVT-AV1
  Source/App/EbTime.h
  Source/Lib/ASM_AVX2/EbMCP16bit_Intrinsic_AVX2.c
  Source/Lib/ASM_AVX2/EbNoiseExtractAVX2.c
  Source/Lib/ASM_AVX2/EbTransforms_Intrinsic_AVX2.c
  Source/Lib/ASM_SSE2/EbMcp16bit_Intrinsic_SSE2.c
  Source/Lib/ASM_SSE2/EbPictureOperators_SSE2.asm
  Source/Lib/ASM_SSE2/EbTransforms_Intrinsic_SSE2.c
  Source/Lib/ASM_SSE2/x64RegisterUtil.asm
  Source/Lib/ASM_SSSE3/EbAvcStyleMcp_Intrinsic_SSSE3.c
  Source/Lib/ASM_SSSE3/EbMcp_Intrinsic_SSSE3.c
  Source/Lib/ASM_SSSE3/EbTransforms_Intrinsic_SSSE3.c
  Source/Lib/Codec/EbCodingLoop.c
  Source/Lib/Codec/EbCodingUnit.h
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbInitialRateControlProcess.c
  Source/Lib/Codec/EbInitialRateControlProcess.h
  Source/Lib/Codec/EbIntraPrediction.c
  Source/Lib/Codec/EbMdRateEstimation.c
  Source/Lib/Codec/EbMdRateEstimation.h
  Source/Lib/Codec/EbModeDecision.c
  Source/Lib/Codec/EbModeDecisionConfiguration.c
  Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Codec/EbModeDecisionProcess.c
  Source/Lib/Codec/EbMotionEstimation.c
  Source/Lib/Codec/EbMotionEstimation.h
  Source/Lib/Codec/EbMotionEstimationContext.c
  Source/Lib/Codec/EbMotionEstimationProcess.c
  Source/Lib/Codec/EbPacketizationProcess.c
  Source/Lib/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Codec/EbPictureDecisionProcess.c
  Source/Lib/Codec/EbPictureManagerProcess.c
  Source/Lib/Codec/EbPictureOperators.c
  Source/Lib/Codec/EbPictureOperators.h
  Source/Lib/Codec/EbProductCodingLoop.c
  Source/Lib/Codec/EbRateDistortionCost.c
  Source/Lib/Codec/EbReferenceObject.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Codec/EbString.c
  Source/Lib/Codec/EbString.h
  Source/Lib/Codec/EbTransforms.c
  Source/Lib/Codec/EbUtility.c
  Source/Lib/Codec/EbUtility.h
Labels: Clean up, build

#437 FFmpeg-Plugin: add high dynamic range
  ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
Labels: ffmpeg

#445 GetAffinityMask: Prefix with EbHevc
  Source/Lib/Codec/EbEncHandle.c
Labels: Clean up

#399 Enabling segment override for each LCU separatelly
  Config/SVTSegmentOvFile.txt
  Config/Sample.cfg
  Docs/svt-hevc_encoder_user_guide.md
  Source/API/EbApi.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppContext.c
  Source/App/EbAppProcessCmd.c
  Source/Lib/Codec/EbCodingLoop.c
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbModeDecisionProcess.c
  Source/Lib/Codec/EbPictureControlSet.c
  Source/Lib/Codec/EbPictureControlSet.h
  Source/Lib/Codec/EbPictureManagerProcess.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
Labels: enhancement

#447 Revert "Fix reading input for fifo in ReadInputFrames"
  Source/App/EbAppInputy4m.c
  Source/App/EbAppProcessCmd.c
Labels: bug

#444 Fix typo
  Source/Lib/Codec/EbPictureManagerProcess.c
Labels: Clean up

#450 Fix macOS build
  Source/App/EbAppProcessCmd.c
Labels: build

#452 Fix interlacedVideo configuration
  Source/Lib/Codec/EbEncHandle.c
Labels: Clean up

#453 Appveyor: Merge Unix+FFmpeg Job and clean up artifacts
  appveyor.yml
Labels: ci
