Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2019-09, with the labels that each got.

#348 New tile group
  Source/Lib/Codec/EbCodingLoop.c
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbEncDecProcess.h
  Source/Lib/Codec/EbEncDecTasks.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEntropyCodingProcess.c
  Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Codec/EbModeDecisionProcess.c
  Source/Lib/Codec/EbModeDecisionProcess.h
  Source/Lib/Codec/EbPictureControlSet.c
  Source/Lib/Codec/EbPictureControlSet.h
  Source/Lib/Codec/EbPictureManagerProcess.c
  Source/Lib/Codec/EbSequenceControlSet.c
  Source/Lib/Codec/EbSequenceControlSet.h
Labels: Clean up

#349 Fix mv out of bounds issue for non-mcts encoding
  Source/Lib/Codec/EbModeDecision.c
Labels: bug

#330 Add the "-thread-count" parameter support
  Config/Sample.cfg
  Docs/svt-hevc_encoder_user_guide.md
  Source/API/EbApi.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppContext.c
  Source/Lib/Codec/EbEncHandle.c
  ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
Labels: enhancement

#354 Appveyor: Fix appveyor builds
  appveyor.yml
Labels: ci

#352 fix umv0 out of bounds issue for high motion cases
  Source/Lib/Codec/EbModeDecision.c
Labels: bug

#356 Appveyor: Add ffmpeg build
  .travis.yml
  appveyor.yml
Labels: ci

#320 Fix wrong bitstream indication for conformance to MainRext
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEntropyCoding.c
Labels: Clean up

#361 Update AppVeyor to only deploy VS19 Release build to GitHub Releases
  appveyor.yml
Labels: ci

#369 Worked around the incorrect tranform issue with AVX unsupported CPU.
  Source/Lib/Codec/EbTransforms.c
Labels: bug
