Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2019-03, with the labels that each got.

#133 FFmpeg Plugin: Add the VMAF optimized mode to "-tune" and the "-hdr" parameter
  ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
Labels: enhancement

#141 Fix YUV420p10 format encoding error.
  Source/Lib/Codec/EbModeDecision.c
Labels: bug

#149 FFmpeg-Plugin: Revert the header file names' change
  ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
Labels: Clean up

#145 Optimize function pointers and duplicate definition of DECODED_PICTURE_HASH
  Source/Lib/Codec/EbAvcStyleMcp.c
  Source/Lib/Codec/EbCodingLoop.c
  Source/Lib/Codec/EbDeblockingFilter.c
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbFullLoop.c
  Source/Lib/Codec/EbIntraPrediction.c
  Source/Lib/Codec/EbMcp.c
  Source/Lib/Codec/EbModeDecision.c
  Source/Lib/Codec/EbMotionEstimation.c
  Source/Lib/Codec/EbMotionEstimationProcess.c
  Source/Lib/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Codec/EbPictureOperators.c
  Source/Lib/Codec/EbProductCodingLoop.c
  Source/Lib/Codec/EbSampleAdaptiveOffsetGenerationDecision.c
  Source/Lib/Codec/EbTransforms.c
Labels: Clean up

#120 install Windows version to C:\svt-hevc by default
  Build/windows/generate_vs17.bat
Labels: Clean up

#113 Allocate resource based on number of logical processor configed.
  Docs/svt-hevc_encoder_user_guide.md
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbThreads.h
Labels: Clean up

#75 #define TILES 1 //enable TILES.
  Config/Sample.cfg
  Source/API/EbApi.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppContext.c
  Source/Lib/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Codec/EbCodingLoop.c
  Source/Lib/Codec/EbCodingUnit.h
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbEntropyCoding.h
  Source/Lib/Codec/EbEntropyCodingProcess.c
  Source/Lib/Codec/EbPictureControlSet.h
  Source/Lib/Codec/EbPictureManagerProcess.c
  Source/Lib/Codec/EbProductCodingLoop.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Codec/EbSequenceControlSet.h
  Source/SimpleApp/EbSimpleAppContext.h
Labels: enhancement

#169 [gst-plugin]Add config for new SVT-HEVC API
  gstreamer-plugin/gstsvthevcenc.c
Labels: bug
