Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2019-10, with the labels that each got.

#336 New Test Cases
  Tests/README.md
  Tests/SVT-HEVC_FunctionalTests.py
Labels: test

#379 Fix y4m check with stdin
  Source/App/EbAppConfig.c
Labels: enhancement

#365 Travis maintenance: Update build environments, FFmpeg
  .travis.yml
Labels: ci

#383 Reverted commits for Issue #371, and fixed SvtHevcEncApp core dumped issue.
  Source/App/EbAppConfig.c
  Source/App/EbAppContext.c
  Source/App/EbAppProcessCmd.c
Labels: Clean up

#380 Fixed the Y4M header analysis issue in SvtHevcEncApp.
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppInputy4m.c
  Source/App/EbAppInputy4m.h
  Source/App/EbAppProcessCmd.c
Labels: bug

#384 User Guide changes
  Docs/svt-hevc_encoder_user_guide.md
Labels: documentation

#387 GStreamer plugin
  gstreamer-plugin/README.md
Labels: documentation

#388 Add --version to sample app
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppMain.c
Labels: Clean up

#391 gstreamer plugin missing dependency fix in CMakeLists.txt
  gstreamer-plugin/CMakeLists.txt
Labels: bug, gstreamer

#381 Fix 8x8 CU scan index error in function `DeriveLcuScore()`.
  Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
Labels: Clean up

#393 Block CompressedTenBitFormat ON for non-420 color format
  Source/App/EbAppConfig.c
  Source/App/EbAppMain.c
Labels: Clean up

#394 Fix cropping info missing in EbH265EncStreamHeader issue
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
Labels: bug

#397 10bit compressed check
  Source/App/EbAppConfig.c
Labels: Clean up

#395 Updated test script
  Tests/README.md
  Tests/SVT-HEVC_FunctionalTests.py
Labels: test

#402 Addressed the SIGFPE issue with VBV settings and CQP rate control mode.
  Source/Lib/Codec/EbEncHandle.c
Labels: bug

#400 FFmpeg-Plugin: add vbv maxrate and bufsize
  ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
Labels: ffmpeg
