Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2019-08, with the labels that each got.

#296 User Guide changes
  Docs/3-layer-hierarchical-low-delay.png
  Docs/3-layer-hierarchical-low-delay2.png
  Docs/3-layer-hierarchical-low-delay3.png
  Docs/svt-hevc_encoder_user_guide.md
Labels: Clean up, documentation

#295 PRINT_HEADER Preprocessor
  Source/App/EbAppInputy4m.c
Labels: Clean up

#294 disable P422 and P444 chroma search for known quality issue
  Source/Lib/Codec/EbModeDecisionProcess.c
Labels: bug

#292 [ASM_SSE2] fixed the output mismatching issue with ASM enabled and disabled (Issue #281).
  Source/Lib/ASM_SSE2/EbSaoStatistics_Intrinsic_SSE2.c
Labels: bug

#300 scan_type is unused but set
  Source/App/EbAppInputy4m.c
Labels: Clean up

#301 Faster M11 8k 4k preset
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Codec/EbPictureDecisionProcess.c
Labels: P1

#306 Add CentOS in README
  README.md
Labels: documentation

#304 Gstreamer plugin: Apply changes to git-patch based on the latest Gstreamer and SVT-HEVC
  gstreamer-plugin/git-patch/0001-svthevcenc-Add-svthevc-encoder-element.patch
Labels: Clean up, gstreamer

#303 Support both dynamic/static builds
  .travis.yml
  Build/linux/build.sh
  CMakeLists.txt
  README.md
  Source/API/EbTime.h
  Source/App/EbAppContext.c
  Source/App/EbAppMain.c
  Source/App/EbAppProcessCmd.c
  Source/App/EbTime.c
  Source/Lib/Codec/CMakeLists.txt
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncHandle.c
  ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
Labels: build, enhancement

#316 UnrestrictedMotionVector
  Config/Sample.cfg
Labels: documentation

#310 CMake: Move version value managing to top of CMakeList.txt
  .gitignore
  CMakeLists.txt
  Source/API/EbApi.h
  Source/API/EbApiVersion.h.in
  Source/Lib/pkg-config.pc.in
Labels: Clean up

#315 Refine and clean up tile related codes
  Source/App/EbAppInputy4m.c
  Source/Lib/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Codec/EbCodingLoop.c
  Source/Lib/Codec/EbCodingUnit.h
  Source/Lib/Codec/EbDeblockingFilter.c
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbEntropyCodingProcess.c
  Source/Lib/Codec/EbInitialRateControlProcess.c
  Source/Lib/Codec/EbIntraPrediction.c
  Source/Lib/Codec/EbModeDecision.c
  Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Codec/EbModeDecisionProcess.c
  Source/Lib/Codec/EbMotionEstimation.c
  Source/Lib/Codec/EbMotionEstimationProcess.c
  Source/Lib/Codec/EbPacketizationProcess.c
  Source/Lib/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Codec/EbPictureControlSet.c
  Source/Lib/Codec/EbPictureControlSet.h
  Source/Lib/Codec/EbPictureManagerProcess.c
  Source/Lib/Codec/EbProductCodingLoop.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Codec/EbSequenceControlSet.c
  Source/Lib/Codec/EbSequenceControlSet.h
  Source/Lib/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Codec/EbUtility.h
Labels: Clean up

#264 Optimize Copy of SequenceControlSet and initial value assignment
  Source/Lib/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Codec/EbSei.c
  Source/Lib/Codec/EbSequenceControlSet.c
  Source/Lib/Codec/EbSequenceControlSet.h
Labels: Clean up

#311 Mingw: Replace some more _MSC_VER with _WIN32
  CMakeLists.txt
  Source/App/EbAppConfig.h
  Source/App/EbAppMain.c
  Source/App/EbTime.c
  Source/Lib/ASM_AVX2/EbCombinedAveragingSAD_Intrinsic_AVX512.c
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbThreads.h
  Source/Lib/Codec/EbUtility.c
Labels: Clean up

#250 Add VPS/SPS/PPS insertion for IDR frames option
  Config/Sample.cfg
  Docs/svt-hevc_encoder_user_guide.md
  Source/API/EbApi.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppContext.c
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbPacketizationProcess.c
  Source/Lib/Codec/EbPictureControlSet.h
  Source/Lib/Codec/EbPictureDecisionProcess.c
  Source/Lib/Codec/EbSequenceControlSet.h
  ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
  ffmpeg_plugin/0002-doc-Add-libsvt_hevc-encoder-docs.patch
  gstreamer-plugin/git-patch/0001-svthevcenc-Add-svthevc-encoder-element.patch
  gstreamer-plugin/gstsvthevcenc.c
Labels: enhancement

#323 Build.sh: Change to use bin sh instead of bash
  Build/linux/build.sh
Labels: Clean up, build

#326 Clean up, add static to local functions
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbInitialRateControlProcess.c
  Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Codec/EbMotionEstimationProcess.c
  Source/Lib/Codec/EbPacketizationProcess.c
  Source/Lib/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Codec/EbPictureAnalysisProcess.h
  Source/Lib/Codec/EbPictureDecisionProcess.c
  Source/Lib/Codec/EbRateControlProcess.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Codec/EbSourceBasedOperationsProcess.c
Labels: Clean up

#333 CMake: Remove Og flag since it doesn't seem to always work properly
  CMakeLists.txt
Labels: build

#334 Appveyor: Add debug and basic encoding tests along with mingw builds
  appveyor.yml
Labels: ci

#312 Remove limitation of less than 16 Sockets
  Source/Lib/Codec/EbEncHandle.c
Labels: Clean up

#328 AMVP: injected the MV candidates with the correct ref list for AMVP.
  Source/Lib/Codec/EbModeDecision.c
Labels: bug
