Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2019-07, with the labels that each got.

#224 Enable tile parallelism
  Source/API/EbApi.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppContext.c
  Source/Lib/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Codec/EbCodingLoop.c
  Source/Lib/Codec/EbCodingUnit.h
  Source/Lib/Codec/EbDeblockingFilter.c
  Source/Lib/Codec/EbDeblockingFilter.h
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbEncDecProcess.h
  Source/Lib/Codec/EbEncDecResults.h
  Source/Lib/Codec/EbEncDecTasks.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbEntropyCoding.h
  Source/Lib/Codec/EbEntropyCodingProcess.c
  Source/Lib/Codec/EbInitialRateControlProcess.c
  Source/Lib/Codec/EbModeDecision.c
  Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Codec/EbModeDecisionProcess.c
  Source/Lib/Codec/EbModeDecisionProcess.h
  Source/Lib/Codec/EbMotionEstimation.c
  Source/Lib/Codec/EbMotionEstimationProcess.c
  Source/Lib/Codec/EbPacketizationProcess.c
  Source/Lib/Codec/EbPictureControlSet.c
  Source/Lib/Codec/EbPictureControlSet.h
  Source/Lib/Codec/EbPictureManagerProcess.c
  Source/Lib/Codec/EbProductCodingLoop.c
  Source/Lib/Codec/EbRateControlTasks.h
  Source/Lib/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Codec/EbSequenceControlSet.c
  Source/Lib/Codec/EbSequenceControlSet.h
Labels: enhancement

#195 SpatialFullDistortionKernel(SSE) fix
  Source/Lib/ASM_AVX2/EbComputeSAD_AVX2.h
  Source/Lib/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/ASM_AVX2/EbComputeSAD_SadLoopKernel_AVX512.c
  Source/Lib/ASM_SSE4_1/EbPictureOperators_Intrinsic_SSE4_1.c
  Source/Lib/Codec/EbComputeSAD.h
Labels: bug

#236 CMakeList: Fix build with CMAKE VERSION < 3.1
  CMakeLists.txt
Labels: Clean up, build

#232 Change PRINT_HEADER usage in y4m
  Source/App/EbAppInputy4m.c
Labels: Clean up

#241 Batch: Fix Bin folder and other issues
  Build/windows/build.bat
  CMakeLists.txt
  README.md
Labels: bug, build

#146 Change nalu file setting
  Source/App/EbAppConfig.c
Labels: Clean up

#233 Fix video corruption with interlaced input
  Source/App/EbAppConfig.c
Labels: bug

#251 Add protection in init segments
  Source/Lib/Codec/EbEncDecSegments.c
Labels: Clean up

#248 Y4m ctype
  Source/App/EbAppInputy4m.c
Labels: Clean up

#252 Stride Checks
  Source/Lib/Codec/EbEncHandle.c
Labels: Clean up

#247 NALU file processing
  Source/App/EbAppProcessCmd.c
  Source/Lib/Codec/EbEncHandle.c
Labels: Clean up

#253 Added encoder mode11 to tune 1(OQ)
  Docs/svt-hevc_encoder_user_guide.md
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbModeDecision.c
  Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Codec/EbPictureDecisionProcess.c
Labels: enhancement

#265 Invalid character in `EbApi.h` and remove duplicate parameter mapping
  Source/API/EbApi.h
  Source/App/EbAppConfig.c
Labels: Clean up

#155 Vbv dev
  Config/Sample.cfg
  Docs/svt-hevc_encoder_user_guide.md
  Source/API/EbApi.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppContext.c
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEncodeContext.c
  Source/Lib/Codec/EbEncodeContext.h
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbEntropyCoding.h
  Source/Lib/Codec/EbInitialRateControlReorderQueue.c
  Source/Lib/Codec/EbPacketizationProcess.c
  Source/Lib/Codec/EbPacketizationProcess.h
  Source/Lib/Codec/EbPacketizationReorderQueue.c
  Source/Lib/Codec/EbPacketizationReorderQueue.h
  Source/Lib/Codec/EbPictureControlSet.c
  Source/Lib/Codec/EbPictureDecisionProcess.c
  Source/Lib/Codec/EbPictureDemuxResults.h
  Source/Lib/Codec/EbPictureManagerProcess.c
  Source/Lib/Codec/EbPictureManagerQueue.h
  Source/Lib/Codec/EbRateControlProcess.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Codec/EbSei.c
  Source/Lib/Codec/EbSei.h
  Source/Lib/Codec/EbSequenceControlSet.c
  Source/Lib/Codec/EbSequenceControlSet.h
Labels: enhancement

#257 STYLE.md
  README.md
  STYLE.md
Labels: Clean up

#268 Address M11 tune 1 items
  Source/App/EbAppConfig.c
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbEncHandle.c
Labels: P1, bug

#263 Deprecate -tune interface
  Config/Sample.cfg
  Docs/encoding_mode_res_table.png
  Docs/svt-hevc_encoder_user_guide.md
  README.md
  Source/API/EbApi.h
  Source/App/EbAppConfig.c
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncHandle.c
  Tests/SVT-HEVC_FunctionalTests.py
  ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
  gstreamer-plugin/gstsvthevcenc.c
Labels: Clean up

#256 Tests README
  Tests/README.md
  Tests/README.txt
Labels: Clean up

#267 Y4m nalu compile issues
  Source/App/EbAppInputy4m.c
  Source/App/EbAppProcessCmd.c
Labels: Clean up

#228 CMake: apply -fstack-protector-strong if not mingw
  CMakeLists.txt
Labels: build

#290 Fix extra M11 test cases in test script
  Tests/SVT-HEVC_FunctionalTests.py
Labels: ci

#291 [travis]Stop applying ffmpeg doc only patch
  .travis.yml
Labels: ci
