Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2019-01, with the labels that each got.

#50 Add non-avx512 support
  Source/API/EbApi.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/Lib/ASM_AVX2/EbCombinedAveragingSAD_Intrinsic_AVX512.c
  Source/Lib/ASM_AVX2/EbCombinedAveragingSAD_Intrinsic_AVX512.h
  Source/Lib/ASM_AVX2/EbComputeSAD_AVX2.h
  Source/Lib/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/ASM_AVX2/EbComputeSAD_SadLoopKernel_AVX512.c
  Source/Lib/ASM_AVX2/EbComputeSAD_SadLoopKernel_AVX512.h
  Source/Lib/ASM_AVX2/EbPackUnPack_Intrinsic_AVX2.c
  Source/Lib/ASM_AVX2/EbPackUnPack_Intrinsic_AVX2.h
  Source/Lib/Codec/EbAvcStyleMcp.c
  Source/Lib/Codec/EbComputeSAD.h
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbMotionEstimation.c
  Source/Lib/Codec/EbPackUnPack.h
  Source/Lib/Codec/EbPictureOperators.c
  Source/Lib/Codec/EbTransforms.c
  Source/SimpleApp/EbSimpleAppContext.h
Labels: enhancement

#52 External api feedback
  .gitignore
  Source/API/EbApi.h
  Source/API/EbTime.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppContext.c
  Source/App/EbAppContext.h
  Source/App/EbAppMain.c
  Source/App/EbAppProcessCmd.c
  Source/App/EbTime.c
  Source/Lib/C_DEFAULT/EbTransforms_C.c
  Source/Lib/C_DEFAULT/EbTransforms_C.h
  Source/Lib/Codec/EbAdaptiveMotionVectorPrediction.c
  Source/Lib/Codec/EbCabacContextModel.c
  Source/Lib/Codec/EbCodingLoop.c
  Source/Lib/Codec/EbDeblockingFilter.c
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbEntropyCoding.h
  Source/Lib/Codec/EbFullLoop.c
  Source/Lib/Codec/EbInitialRateControlProcess.c
  Source/Lib/Codec/EbInitialRateControlReorderQueue.h
  Source/Lib/Codec/EbModeDecision.c
  Source/Lib/Codec/EbModeDecisionConfiguration.c
  Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Codec/EbModeDecisionProcess.c
  Source/Lib/Codec/EbMotionEstimation.c
  Source/Lib/Codec/EbMotionEstimationProcess.c
  Source/Lib/Codec/EbPacketizationProcess.c
  Source/Lib/Codec/EbPictureControlSet.h
  Source/Lib/Codec/EbPictureDecisionProcess.c
  Source/Lib/Codec/EbPictureManagerProcess.c
  Source/Lib/Codec/EbPictureOperators.c
  Source/Lib/Codec/EbProductCodingLoop.c
  Source/Lib/Codec/EbRateControlProcess.c
  Source/Lib/Codec/EbRateDistortionCost.c
  Source/Lib/Codec/EbReferenceObject.h
  Source/Lib/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Codec/EbTransforms.c
  Source/Lib/Codec/EbTransforms.h
  Source/SimpleApp/EbSimpleAppContext.c
  Source/SimpleApp/EbSimpleAppContext.h
  Source/SimpleApp/EbSimpleAppMain.c
Labels: enhancement

#62 Enable sharpness for sub 4k
  Source/Lib/Codec/EbCodingLoop.c
  Source/Lib/Codec/EbPictureDecisionProcess.c
Labels: enhancement

#60 Removed HME0, HME1, HME2 config
  Config/Sample.cfg
  Docs/SVT-HEVC_Encoder_User_Guide.pdf
  Source/API/EbApi.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppContext.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbMotionEstimationProcess.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
  Source/SimpleApp/EbSimpleAppContext.h
Labels: Clean up

#63 Enable Move SC feature for OQ 720 and above only
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbMotionEstimation.c
  Source/Lib/Codec/EbMotionEstimationContext.c
  Source/Lib/Codec/EbMotionEstimationContext.h
  Source/Lib/Codec/EbMotionEstimationProcess.c
Labels: enhancement

#68 Add API for FPS in VPS
  Config/Sample.cfg
  Source/API/EbApi.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppContext.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEntropyCoding.c
  Source/SimpleApp/EbSimpleAppContext.h
Labels: enhancement

#69 Add macro to revert the Limit Intra MPM patch
  Source/Lib/Codec/EbModeDecision.c
Labels: bug

#73 Add api for switch to real time and warning update
  Config/Sample.cfg
  Docs/SVT-HEVC_Encoder_User_Guide.pdf
  Source/API/EbApi.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppContext.c
  Source/App/EbAppProcessCmd.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbProductCodingLoop.c
  Source/SimpleApp/EbSimpleAppContext.h
Labels: Clean up

#78 Fix the crash if command input error
  Source/SimpleApp/EbSimpleAppContext.c
  Source/SimpleApp/EbSimpleAppMain.c
Labels: bug

#80 Fix the dump recon mismatch for non-dlf/SAO case
  Source/Lib/Codec/EbCodingLoop.c
  Source/Lib/Codec/EbEncDecProcess.c
Labels: bug
