Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2019-06, with the labels that each got.

#214 Fix writeUvlc long bits bigger than 32 issue and Period SEI error
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbSei.c
Labels: bug

#213 y4m container support in SVT-HEVC
  Docs/svt-hevc_encoder_user_guide.md
  Source/App/CMakeLists.txt
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppInputy4m.c
  Source/App/EbAppInputy4m.h
  Source/App/EbAppProcessCmd.c
Labels: enhancement

#222 Changing default value for fpsInVps to TRUE
  Config/Sample.cfg
  Docs/svt-hevc_encoder_user_guide.md
  Source/App/EbAppConfig.c
  Source/Lib/Codec/EbEncHandle.c
Labels: Clean up

#206 Cmakelists: Redo the lists
  CMakeLists.txt
  Source/App/CMakeLists.txt
  Source/Lib/ASM_AVX2/CMakeLists.txt
  Source/Lib/ASM_SSE2/CMakeLists.txt
  Source/Lib/ASM_SSE4_1/CMakeLists.txt
  Source/Lib/ASM_SSSE3/CMakeLists.txt
  Source/Lib/CMakeLists.txt
  Source/Lib/C_DEFAULT/CMakeLists.txt
  Source/Lib/Codec/CMakeLists.txt
  Source/Lib/pkg-config.pc.in
  gstreamer-plugin/CMakeLists.txt
Labels: Clean up, build

#216 build.bat: fix multifolder, add changes from av1
  Build/windows/build.bat
Labels: Clean up, build

#225 fixed buffer period sei error
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbSei.c
Labels: bug

#136 Travis: port changes from SVT-AV1
  .travis.yml
Labels: ci
