Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2019-02, with the labels that each got.

#86 Fix the frame-rate computation potential overflow issue.
  Source/Lib/Codec/EbEncHandle.c
Labels: bug

#94 Fix linux kw
  Source/App/EbAppConfig.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbInitialRateControlProcess.c
  Source/Lib/Codec/EbInterPrediction.c
  Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Codec/EbProductCodingLoop.c
  Source/Lib/Codec/EbSourceBasedOperationsProcess.c
  Source/Lib/Codec/EbThreads.c
  Source/Lib/Codec/EbTransforms.c
  Source/SimpleApp/EbSimpleAppMain.c
Labels: Clean up

#97 Fix kw issues
  Source/App/EbAppConfig.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbMotionEstimation.c
  Source/Lib/Codec/EbProductCodingLoop.c
  Source/Lib/Codec/EbRateControlProcess.c
Labels: Clean up

#76 Add support for external SEI messages
  Config/Sample.cfg
  Docs/svt-hevc_encoder_user_guide.md
  Source/API/EbApi.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppContext.c
  Source/App/EbAppProcessCmd.c
  Source/Lib/Codec/EbBitstreamUnit.c
  Source/Lib/Codec/EbBitstreamUnit.h
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbEntropyCoding.h
  Source/Lib/Codec/EbPacketizationProcess.c
  Source/Lib/Codec/EbPictureBufferDesc.h
  Source/Lib/Codec/EbSei.c
  Source/Lib/Codec/EbSei.h
  Source/Lib/Codec/EbSequenceControlSet.c
  Source/Lib/Codec/EbSequenceControlSet.h
Labels: enhancement

#91 Fix the multi-thread issue while dumping recon
  Source/Lib/Codec/EbEncDecProcess.c
Labels: bug

#101 Fix conformance error for rbsp_stop_one_bit
  Source/Lib/Codec/EbEntropyCoding.c
Labels: bug

#71 AVX2 intrinsic optimization
  Source/Lib/ASM_AVX2/EbMCP16bit_Intrinsic_AVX2.c
  Source/Lib/ASM_AVX2/EbMcp_AVX2.h
  Source/Lib/ASM_AVX2/EbTransforms_AVX2.h
  Source/Lib/ASM_AVX2/EbTransforms_Intrinsic_AVX2.c
  Source/Lib/ASM_SSE2/EbTransforms_Intrinsic_SSE2.c
  Source/Lib/ASM_SSE4_1/EbTransforms_Intrinsic_SSE4_1.c
  Source/Lib/ASM_SSE4_1/EbTransforms_SSE4_1.h
  Source/Lib/ASM_SSSE3/EbMcp_Intrinsic_SSSE3.c
  Source/Lib/ASM_SSSE3/EbMcp_SSSE3.h
  Source/Lib/C_DEFAULT/EbMcp_C.c
  Source/Lib/C_DEFAULT/EbMcp_C.h
  Source/Lib/Codec/EbCoeffEstimation_Intrinsic.c
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbEntropyCoding.h
  Source/Lib/Codec/EbMcp.c
  Source/Lib/Codec/EbMcp.h
  Source/Lib/Codec/EbMcpTables.c
  Source/Lib/Codec/EbTransforms.c
  Source/Lib/Codec/EbTransforms.h
Labels: enhancement

#105 Add 422/444 support
  Source/API/EbApi.h
  Source/App/EbAppConfig.c
  Source/App/EbAppConfig.h
  Source/App/EbAppContext.c
  Source/App/EbAppProcessCmd.c
  Source/Lib/ASM_AVX2/EbIntraPrediction_AVX2.h
  Source/Lib/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
  Source/Lib/ASM_AVX2/EbNoiseExtractAVX2.c
  Source/Lib/ASM_SSE2/EbIntraPrediction16bit_Intrinsic_SSE2.c
  Source/Lib/ASM_SSE2/EbIntraPrediction_Intrinsic_SSE2.c
  Source/Lib/ASM_SSE2/EbIntraPrediction_SSE2.h
  Source/Lib/ASM_SSSE3/EbIntraPrediction16bit_Intrinsic_SSSE3.c
  Source/Lib/C_DEFAULT/EbDeblockingFilter_C.c
  Source/Lib/C_DEFAULT/EbTransforms_C.c
  Source/Lib/Codec/EbCodingLoop.c
  Source/Lib/Codec/EbCodingUnit.c
  Source/Lib/Codec/EbDeblockingFilter.c
  Source/Lib/Codec/EbDeblockingFilter.h
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbEncDecProcess.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbEntropyCodingUtil.h
  Source/Lib/Codec/EbInterPrediction.c
  Source/Lib/Codec/EbIntraPrediction.c
  Source/Lib/Codec/EbIntraPrediction.h
  Source/Lib/Codec/EbMcp.c
  Source/Lib/Codec/EbModeDecision.c
  Source/Lib/Codec/EbModeDecisionProcess.c
  Source/Lib/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Codec/EbPictureBufferDesc.c
  Source/Lib/Codec/EbPictureBufferDesc.h
  Source/Lib/Codec/EbPictureControlSet.c
  Source/Lib/Codec/EbPictureControlSet.h
  Source/Lib/Codec/EbProductCodingLoop.c
  Source/Lib/Codec/EbRateDistortionCost.c
  Source/Lib/Codec/EbReferenceObject.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Codec/EbSampleAdaptiveOffsetGenerationDecision.c
  Source/Lib/Codec/EbSequenceControlSet.c
  Source/Lib/Codec/EbSequenceControlSet.h
  Source/Lib/Codec/EbTransQuantBuffers.c
  Source/Lib/Codec/EbTransformUnit.h
  Source/SimpleApp/EbSimpleAppContext.c
  Source/SimpleApp/EbSimpleAppContext.h
  Source/SimpleApp/EbSimpleAppMain.c
Labels: enhancement
