Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2020-04, with the labels that each got.

#517 pkg-config: use CMAKE_INSTALL_FULL for ${prefix}
  Source/Lib/pkg-config.pc.in
Labels: build

#522 ffmpeg plugin: expose parameter tile_row_cnt tile_col_cnt and tile_slice_mode
  ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
Labels: ffmpeg

#518 Increase MEM_ENTRY_SIZE
  Source/Lib/Codec/EbMalloc.c
Labels: bug

#475 Fixed the encoding random hang issue with few threads.
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbInitialRateControlProcess.c
  Source/Lib/Codec/EbPictureDecisionProcess.c
  Source/Lib/Codec/EbRateControlProcess.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
Labels: bug

#526 Appveyor: Disable artifact uploading for now
  appveyor.yml
Labels: ci

#524 Fix typo in PK
  Source/Lib/Codec/EbPacketizationProcess.c
Labels: Clean up

#523 Fix hang caused by OUT_ALLOC and remove macro
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbInitialRateControlProcess.c
  Source/Lib/Codec/EbPacketizationProcess.c
  Source/Lib/Codec/EbSequenceControlSet.h
Labels: bug

#527 App/EbAppContext.c: Remove unused AllocateOutputBuffers
  Source/App/EbAppContext.c
  Source/App/EbAppContext.h
Labels: Clean up
