Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2020-02, with the labels that each got.

#466 ffmpeg plugin: add para umv
  ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
Labels: ffmpeg

#468 Add OVC Dockerfiles link
  README.md
Labels: documentation

#480 Optimize MaxNumReorderPics in vps/sps
  Source/Lib/Codec/EbEntropyCoding.c
Labels: enhancement
