Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2020-05, with the labels that each got.

#530 Update the Y sample buffer indexing for position A in Motion Estimation.
  Source/Lib/Codec/EbMotionEstimation.c
Labels: Clean up

#534 Adjust PAREF_OUT
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
Labels: bug

#536 Test Script COMPARE
  Tests/SVT-HEVC_FunctionalTests.py
Labels: test

#537 Uninitialized memory fix
  Source/App/EbAppConfig.c
Labels: Clean up

#538 Add more details of header insertion in user guide
  Docs/svt-hevc_encoder_user_guide.md
Labels: documentation
