Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2020-07, with the labels that each got.

#550 Add PR template
  .github/pull_request_template.md
  README.md
Labels: documentation

#554 Fix -level 0 error checking
  Source/Lib/Codec/EbEncHandle.c
Labels: bug

#558 Expand the precision of bitrate in log print
  Source/App/EbAppMain.c
Labels: Clean up

#555 Add more explanation for -segment-ov parameter
  Config/SVTSegmentOvFile.txt
  Docs/svt-hevc_encoder_user_guide.md
Labels: documentation

#560 Fix klocwork warning
  Source/App/EbAppMain.c
  Source/App/EbAppProcessCmd.c
  Source/Lib/Codec/EbEncHandle.c
Labels: Clean up

#563 Update user guide
  Docs/svt-hevc_encoder_user_guide.md
Labels: documentation

#565 Fix static analysis warning
  Source/App/EbAppProcessCmd.c
  Source/Lib/Codec/EbEncHandle.c
Labels: Clean up
