Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2020-01, with the labels that each got.

#454 Gstreamer plugin: Update several properties to gstreamer style
  gstreamer-plugin/git-patch/0001-svthevcenc-Add-svthevc-encoder-element.patch
  gstreamer-plugin/git-patch/README.txt
  gstreamer-plugin/gstsvthevcenc.c
  gstreamer-plugin/gstsvthevcenc.h
Labels: gstreamer

#456 Improve tune warning
  Source/Lib/Codec/EbEncHandle.c
Labels: Clean up

#462 Fixed the encoding crash issue when width < height.
  Source/Lib/Codec/EbEncDecSegments.c
  Source/Lib/Codec/EbEncHandle.c
Labels: bug

#457 Fixed output buffer too small issue
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEntropyCoding.c
  Source/Lib/Codec/EbEntropyCoding.h
  Source/Lib/Codec/EbInitialRateControlProcess.c
  Source/Lib/Codec/EbPacketizationProcess.c
Labels: bug

#464 ffmpeg plugin: reported error code from invalid packet.
  ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
Labels: Clean up

#455 Fixed the encoding R2R issue with "-lad 0" option.
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
Labels: bug
