Repository OpenVisualCloud/SVT-HEVC, pull requests merged in 2020-03, with the labels that each got.

#486 Change icc compiler ordering
  Build/linux/build.sh
Labels: Clean up, build

#487 Clean up useless function
  Source/Lib/Codec/EbEncHandle.c
Labels: Clean up

#493 appveyor: update pacman packages along with installing them
  appveyor.yml
Labels: ci

#409 Fix condition to prevent encoding two AUD in one IDR frame.
  Source/Lib/Codec/EbPacketizationProcess.c
Labels: Clean up

#494 Disable OUT_ALLOC which causes hang for several cases
  Source/Lib/Codec/EbDefinitions.h
Labels: bug

#503 y4m file rewind logic
  Source/App/EbAppInputy4m.c
Labels: bug

#492 Refined the DEADLOCK_DEBUG outputs in each encoding stage.
  Source/Lib/Codec/EbDefinitions.h
  Source/Lib/Codec/EbEncDecProcess.c
  Source/Lib/Codec/EbEntropyCodingProcess.c
  Source/Lib/Codec/EbInitialRateControlProcess.c
  Source/Lib/Codec/EbModeDecisionConfigurationProcess.c
  Source/Lib/Codec/EbMotionEstimationProcess.c
  Source/Lib/Codec/EbPacketizationProcess.c
  Source/Lib/Codec/EbPictureAnalysisProcess.c
  Source/Lib/Codec/EbPictureDecisionProcess.c
  Source/Lib/Codec/EbPictureManagerProcess.c
  Source/Lib/Codec/EbRateControlProcess.c
  Source/Lib/Codec/EbResourceCoordinationProcess.c
  Source/Lib/Codec/EbSourceBasedOperationsProcess.c
Labels: Clean up

#504 Compile warnings
  Source/Lib/Codec/EbEncHandle.c
  Source/Lib/Codec/EbEntropyCoding.c
Labels: Clean up

#500 Handle corner case of sad64x64 comparison
  Source/Lib/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
  Source/Lib/ASM_AVX2/EbComputeSAD_SadLoopKernel_AVX512.c
  Source/Lib/C_DEFAULT/EbComputeSAD_C.c
Labels: bug
